Fix updateMapData.js by setting header (#388)
We were getting errors like this because we weren't setting `User-Agent`
- oops!

```
HttpError: body used already for: https://nominatim.openstreetmap.org/search?addressdetails=1&q=Byesville%2C+OH%2C+US&format=json
    at /home/runner/work/reform-map/reform-map/node_modules/node-geocoder/lib/httpadapter/fetchadapter.js:58:15
    at tryCatcher (/home/runner/work/reform-map/reform-map/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/reform-map/reform-map/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/reform-map/reform-map/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/reform-map/reform-map/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/reform-map/reform-map/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/runner/work/reform-map/reform-map/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/work/reform-map/reform-map/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/reform-map/reform-map/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/runner/work/reform-map/reform-map/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21) {
  code: undefined
}
```